function delta_NPV = compute_delta_NPV_swap(ratesSet, dates, discounts, start_date, coarse)
% COMPUTE_DELTA_NPV_SWAP - Builds the sensitivity matrix for hedging instruments
%
% This function calculates how the Net Present Value (NPV) of three standard 
% Par Swaps (2y, 6y, and 10y) changes when subjected to the triangular 
% market shocks defined in the coarse DV01 analysis. 
%
% INPUTS:
%   ratesSet   - [Struct] Contains market rates
%   dates      - [Vector] Date grid from the baseline bootstrap curve
%   discounts  - [Vector] Discount factors from the baseline bootstrap curve
%   start_date - [Scalar] Valuation date for the hedging swaps
%   coarse     - [Struct] Result from coarse_DV01_triangular containing:
%                .bumped_discs: {1x3 Cell} of discount factors after shocks
%
% OUTPUT:
%   delta_NPV  - [3x3 Matrix] Sensitivity Matrix:
%                Rows (i): The Hedging Swaps (2y, 6y, 10y).
%                Cols (j): The Market Risk Buckets (0-2y, 2-6y, 6-10y).
% -------------------------------------------------------------------------

    % Define the specific maturities for the hedging instruments (Interest Rate Swaps)
    target_mats = [2, 6, 10];
    
    % Extract the market Swap rates for these maturities to set the fixed legs
    swap_rates  = ratesSet.swaps(target_mats); 
    
    % Pre-allocate the sensitivity matrix
    delta_NPV = zeros(3);
    
    % Nested Sensitivity Loop
    % Outer Loop (i): Iterates through each hedging instrument
    for i = 1:3 
        % Calculate adjusted and unadjusted maturity dates for the i-th swap.
        mat_date_unadj = start_date + datenum(years(target_mats(i)));
        mat_date_adj   = business_date_offset(mat_date_unadj);
        
        % Calculate baseline metrics (Price and BPV) under the current market curve
        df_base  = get_discount_factor_by_zero_rates_linear_interp(start_date, mat_date_adj, dates, discounts);
        BPV_base = BasisPointValueFloating(start_date, mat_date_unadj, dates, discounts);

        % Inner Loop (j): Iterates through each triangular market shock (the "Buckets").
        for j = 1:3 
            % Access the discount factor vector generated by the j-th triangular shock
            bumped_d = coarse.bumped_discs{j}; 
            
            % Calculate bumped metrics for the i-th swap under the j-th curve shock.
            df_bump     = get_discount_factor_by_zero_rates_linear_interp(start_date, mat_date_adj, dates, bumped_d);
            BPV_shifted = BasisPointValueFloating(start_date, mat_date_unadj, dates, bumped_d);
            
            % We compute the sensitivity of hedging instrument 'i' to shock 'j'
            delta_NPV(i, j) = -(df_bump - df_base) - swap_rates(i) * (BPV_shifted - BPV_base);
        end
    end
end
    



    
